name: li_ml
channels:
- defaults
dependencies:
- pip=22.3.1
- python=3.9.2
- pip:
  - matminer==0.8.0
  - cbfv==1.1.0
  - crabnet==2.0.7
  - smact==2.5.0
  - click==8.1.3
  - mat-discover==2.2.3
  - rsa==4.9
  - sniffio==1.3.0
  - pyrsistent==0.19.3
  - mp-api==0.30.5
  - jsonschema==4.17.3
  - ax-platform==0.3.0
  - annotated-types==0.5.0
  - pydantic-core==2.4.0
  - pymatgen==2022.11.7
